BOOTREQUEST   = 1
BOOTREPLY     = 2

DHCPDISCOVER  = 1
DHCPOFFER     = 2
DHCPREQUEST   = 3
DHCPDECLINE   = 4
DHCPACK       = 5
DHCPNAK       = 6
DHCPRELEASE   = 7
DHCPINFORM    = 8

DHCPOPT_NETMASK        = 1
DHCPOPT_GATEWAY        = 3
DHCPOPT_RESOLVER       = 6
DHCPOPT_HOSTNAME       = 12
DHCPOPT_DOMAIN         = 15
DHCPOPT_BROADCAST      = 28
DHCPOPT_IPADDR         = 50
DHCPOPT_LEASE_TIME     = 51
DHCPOPT_MSG_TYPE       = 53
DHCPOPT_MSG_PARA       = 55